### ISSUE TITLE
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Unknown animation

### ISSUE THREAD

**Issue by exaxeeae** [SolarLune/bdx#27]
i cant play 3D animation ; BDX cant find my ; excuse my English

**Comment by rafcolson** [comment]
This probably is a duplicate of https://github.com/GoranM/bdx/issues/1042

**Comment by SolarLune** [comment]
Yeah, I'd guess so. 

Please feel free to report bugs on the "original master", on Goran's branch.
